# 7.1 Simulacao de muitos passeios aleatorios ao mesmo tempo

In [128]:
import numpy as np
from matplotlib.pyplot import hist2d

Se o que voce desaja e simular muitos passeios aleatoriso,  digamos cinco mil pode gerar todos eles fazendo poucas modificacoes no codigo anterior. Se receberem uma tupla de dois elementosm as fincoes de `numpy.random` gerarao um array bidimencional de arremessos de moeda e poderemos calcular a soma cumulativa para cada linha e tambem todos as 5000 passos aleatorios de uma vez so

In [148]:
rng = np.random.default_rng(123445)

In [149]:
nwalk = 5_000

In [150]:
nsteps = 1_000

In [151]:
draws = rng.integers(0, 2, size=(nwalk,  nsteps))

In [152]:
steps = np.where(draws > 0, 1, -1)

In [153]:
walks = steps. cumsum(axis = 1)

In [155]:
print(walks)

[[ -1  -2  -1 ...  -6  -7  -6]
 [  1   0  -1 ...  40  41  40]
 [  1   0  -1 ...  -6  -7  -6]
 ...
 [ -1   0   1 ...  50  51  50]
 [  1   0  -1 ... -26 -27 -26]
 [  1   2   1 ...  -4  -5  -4]]


In [156]:
walks.max()

np.int64(115)

In [157]:
walks.min()

np.int64(-116)

Vamos calcular o tempo minimo de travessia para a chegada a 30 ou -30 passos. Isso e um pouco complicado porque nem todos os 5.000 passeios alcancam 30. podemos fazer a verificacao usando ometodo any:

In [158]:
hits30 = (np.abs(walks) >= 30).any(axis = 1)

In [159]:
hits30

array([False,  True,  True, ...,  True,  True,  True], shape=(5000,))

In [160]:
hits30.sum()

np.int64(3348)

POdemos usar esse array booleano para selecionar as linhas de passeios (walks) que realmente cruzaram o nivel absoluto de 30 e chamamos `argmax` no eixo 1 para obter os tempos travessia:

In [161]:
crosing_times = (np.abs(walks[hits30])>= 30).argmax(axis = 1)

In [162]:
crosing_times

array([911, 685, 447, ..., 613, 233, 809], shape=(3348,))

Por fim vamos calcular a media dos tempos de travessia

In [163]:
crosing_times.mean()

np.float64(504.0818399044206)