# 1.9 Transposicao de arrays e trocas de eixo

In [24]:
import numpy as np

A trans posicao e uma forma especial de reformatacao que tenha tambem reorna uma visaualisacao dos dados subjacentes, sem fazer nenhuma copia. Os arrays tem o metodo trenspose e o atributo especial T

In [25]:
arr = np.arange(15).reshape((3, 5))

In [27]:
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [29]:
print(arr.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


Ao fazer calculo com matriz talvez voce use esse recurso com alguma frequancia por exemplo,  ao calcular da matriz inversa interna usando `numpy. dot`

In [30]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0 , 1]])

In [32]:
print(np.dot(arr.T,  arr))

[[39 20 12]
 [20 14  2]
 [12  2 10]]


Opercao infixo `@` e outra maneira para fazermos a multiplicacao de matrizeis:

In [34]:
print(arr.T @ arr)

[[39 20 12]
 [20 14  2]
 [12  2 10]]


A transposicao simpes com `.T` e um caso especifico de troca de eixos. O ndarraytem o metodo `swapaxes`,  que recebe um par de numeros de eixo e troca os eixos indicados para reorganisar os dados

In [36]:
print(arr)

[[ 0  1  0]
 [ 1  2 -2]
 [ 6  3  2]
 [-1  0 -1]
 [ 1  0  1]]


In [38]:
print(arr.swapaxes(0, 1))

[[ 0  1  6 -1  1]
 [ 1  2  3  0  0]
 [ 0 -2  2 -1  1]]


O metodo `swapaxes` tamnem retorna uma visualisacao dos dados sem fazer copia