# 2.1 Pseudo-Random Number Generation

In [1]:
import numpy as np
from random import normalvariate

The `numpy.random` module is NumPy's suite for generating random numbers and is generally much faster than Python's built-in `random` module for generating large sequences.

In [2]:
N = 1_000_000
# Timing Python's random module
%timeit [normalvariate(0, 1) for _ in range(N)]
# Timing NumPy's random module
%timeit np.random.standard_normal(N)

[[ 0.48725968 -1.28692215  0.77035769  0.00854049]
 [-1.66876113 -1.04000979  0.31276526 -0.24871181]
 [-1.8082471   0.13103773 -0.91408356  0.38227725]
 [ 0.58543561 -0.56414     1.86404783 -0.87213939]]


## 2.1.1 The Random Generator

The modern way to generate random numbers in NumPy is with a **Generator** instance. You create a generator, optionally with a `seed` for reproducibility.

In [4]:
rng = np.random.default_rng(seed=12345)
print(f"Generator type: {type(rng)}")

389 ms ± 5.96 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## 2.1.2 Common Generator Methods

#### `standard_normal`
Draws samples from a standard normal distribution (mean 0, variance 1).

In [ ]:
print(f"A 2x3 array of standard normal samples:\n{rng.standard_normal((2, 3))}")

#### `permutation`
Returns a random permutation of a sequence or a permuted range.

In [ ]:
print(f"Permuted range: {rng.permutation(10)}")

#### `shuffle`
Modifies a sequence in-place by shuffling its contents.

In [ ]:
arr = np.arange(10)
rng.shuffle(arr)
print(f"Shuffled array: {arr}")

#### `uniform`
Draws samples from a uniform distribution over `[low, high)`.

In [8]:
print(f"Uniform sample between 0 and 10: {rng.uniform(low=0.0, high=10.0)}")

#### `integers`
Draws random integers from a given range.

In [9]:
print(f"Three random integers between 0 and 10: {rng.integers(low=0, high=10, size=3)}")

Permuted range: [4 8 1 3 7 9 6 0 2 5]
Permuted array: [0 9 3 5 2 6 1 8 7 4]


## 2.1.3 Other Distributions

The generator provides methods for many other probability distributions.

#### `binomial`
Draws samples from a binomial distribution.

In [11]:
print(f"Binomial samples: {rng.binomial(10, 0.5, 3)}")

Uniform sample: 2.201349555454862


#### `normal`
Draws samples from a normal (Gaussian) distribution with a specified mean (`loc`) and standard deviation (`scale`).

In [12]:
print(f"Normal samples: {rng.normal(loc=10, scale=0.5, size=3)}")

Random integers: [7 0 3]


#### `beta`
Draws samples from a beta distribution.

In [13]:
print(f"Beta samples: {rng.beta(10, 0.5, 3)}")


Standard normal sample: 0.9029193414250598
Standard normal array: [-1.62158273 -0.15818926  0.44948393 -1.34360107 -0.08168759  1.72473993
  2.61815943  0.77736134  0.8286332  -0.95898831]


NumPy provides a wide range of functions for generating samples from many other probability distributions.