# 2.1 Pseudo-Random Number Generation

In [1]:
import numpy as np

The `numpy.random` module supplements the built-in Python `random` module with functions for efficiently generating whole arrays of sample values from many kinds of probability distributions.

In [2]:
# Generate a 4x4 array of samples from the standard normal distribution
samples = np.random.standard_normal(size=(4, 4))
print(samples)

[[ 0.48725968 -1.28692215  0.77035769  0.00854049]
 [-1.66876113 -1.04000979  0.31276526 -0.24871181]
 [-1.8082471   0.13103773 -0.91408356  0.38227725]
 [ 0.58543561 -0.56414     1.86404783 -0.87213939]]


In contrast, Python's built-in `random` module only samples one value at a time. As you can see in a simple benchmark, `numpy.random` is well over an order of magnitude faster for generating very large samples.

In [3]:
from random import normalvariate

N = 1_000_000

In [4]:
# Timing the Python's random module
%timeit [normalvariate(0, 1) for _ in range(N)]

389 ms ± 5.96 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
# Timing NumPy's random module
%timeit np.random.standard_normal(N)

15.6 ms ± 77.3 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## 2.1.1 The Random Generator

We call these numbers *pseudo-random* because they are generated by a configurable random number generator that deterministically creates values. You can configure the generator's initial state by setting a `seed`.

In [6]:
# Create a new random number generator with a seed
rng = np.random.default_rng(seed=12345)

# Generate data from the new generator
data = rng.standard_normal((2, 3))
print(data)

[[-1.42382504  1.26372846 -0.87066174]
 [-0.25917323 -0.07534331 -0.74088465]]


The `seed` determines the initial state of the generator, and the state changes each time the `rng` object is used to generate data. This `rng` object is isolated from other code that might be using `numpy.random`.

In [7]:
type(rng)

numpy.random._generator.Generator

## 2.1.2 Common Generator Methods

Here are some of the most common methods available for random generator objects like `rng`.

In [8]:
rng = np.random.default_rng(seed=12345)

### `permutation`
Returns a random permutation of a sequence, or a permuted range.

In [9]:
# Permutation of a range
print(f"Permuted range: {rng.permutation(10)}")

# Permutation of an array
arr = np.arange(10)
print(f"Permuted array: {rng.permutation(arr)}")

Permuted range: [4 8 1 3 7 9 6 0 2 5]
Permuted array: [0 9 3 5 2 6 1 8 7 4]


### `shuffle`
Modifies a sequence in-place by shuffling its contents.

In [10]:
arr = np.arange(10)
rng.shuffle(arr)
print(f"Shuffled array: {arr}")

Shuffled array: [0 1 5 8 3 9 7 6 2 4]


### `uniform`
Draws samples from a uniform distribution.

In [11]:
# A single value between 0 and 10
print(f"Uniform sample: {rng.uniform(low=0.0, high=10.0)}")

Uniform sample: 2.201349555454862


### `integers`
Draws random integers from a given range.

In [12]:
# Three random integers between 0 and 10
print(f"Random integers: {rng.integers(low=0, high=10, size=3)}")

Random integers: [7 0 3]


### `standard_normal`
Draws samples from a standard normal distribution (mean 0, standard deviation 1).

In [13]:
# A single value
print(f"Standard normal sample: {rng.standard_normal()}")

# An array of 10 values
print(f"Standard normal array: {rng.standard_normal(10)}")

Standard normal sample: 0.9029193414250598
Standard normal array: [-1.62158273 -0.15818926  0.44948393 -1.34360107 -0.08168759  1.72473993
  2.61815943  0.77736134  0.8286332  -0.95898831]


### Other Distributions

NumPy provides a wide range of functions for generating samples from many other probability distributions.

In [14]:
# Binomial distribution
print(f"Binomial samples: {rng.binomial(10, 0.5, 3)}")

# Normal (Gaussian) distribution
print(f"Normal samples: {rng.normal(loc=10, scale=0.5, size=3)}")

# Beta distribution
print(f"Beta samples: {rng.beta(10, 0.5, 3)}")


Binomial samples: [6 7 7]
Normal samples: [10.3759697   9.67061984  9.38566251]
Beta samples: [0.95533627 0.98783873 0.99968014]
