# 1.1) NumPy ndarray: A Multidimensional Array Object

One of NumPy's key features is its N-dimensional array object, or `ndarray`, which is a fast and flexible container for large datasets in Python.

Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to the equivalent operations between scalar elements.

To give you a flavor of how NumPy enables batch computations with similar syntax to scalar values on built-in Python objects, I first import NumPy and generate a small array:

In [1]:
import numpy as np

In [2]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [3]:
print(data)

[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]


### Mathematical Operations
You can write mathematical operations with `data` just like you would with a single number:

In [4]:
# Multiplying all elements by 10
print(data * 10)

[[ 15.  -1.  30.]
 [  0. -30.  65.]]


In [5]:
# Adding the array to itself
print(data + data)

[[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]


In the first example, all elements were multiplied by 10. In the second, the corresponding values in each cell were added together.

### Array Attributes
An `ndarray` is a generic multidimensional container for **homogeneous data**; that is, all elements must be of the same type.

Every array has two key attributes:
1. `shape`: A tuple indicating the size of each dimension.
2. `dtype`: An object describing the data type of the array.

In [6]:
data.shape

(2, 3)

In [7]:
size = data.shape

In [8]:
print(f"rows = {size[0]}  \ncolumns = {size[1]}")

rows = 2  
columns = 3


In [9]:
data.dtype

dtype('float64')

### Conclusion
Throughout this guide, we will explore the basics of using NumPy arrays. While deep knowledge of NumPy isn't always required for high-level tools like Pandas, becoming proficient in **array-oriented programming** is a key step to becoming a scientific Python guru.
