# 1.2 Creating ndarrays

In [11]:
import numpy as np

## 1.2.1 Creating Arrays from Existing Data

#### `np.array`
Converts a sequence-like object (like a list) into an `ndarray`.

In [12]:
data = [[1, 2, 3], [4, 5, 6]]
arr = np.array(data)
print(f"2D Array:\n{arr}")

2D Array:
[[1 2 3]
 [4 5 6]]


#### `np.asarray`
Converts the input to an `ndarray`, but does **not** create a copy if the input is already an `ndarray`.

In [13]:
arr_no_copy = np.asarray(arr)
print(f"arr_no_copy is arr: {arr_no_copy is arr}")

arr_no_copy is arr: True


## 1.2.2 Creating Arrays from Scratch

#### `zeros`
Creates an array of a given shape filled with `0`s.

In [14]:
print(f"A 2x3 array of zeros:\n{np.zeros((2, 3))}")

A 2x3 array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]]


#### `ones`
Creates an array of a given shape filled with `1`s.

In [15]:
print(f"A 1D array of ones: {np.ones(5)}")

A 1D array of ones: [1. 1. 1. 1. 1.]


#### `empty`
Creates an array without initializing its values. It contains uninitialized "garbage" data.

In [16]:
print(f"An empty 2x2 array:\n{np.empty((2, 2))}")

An empty 2x2 array:
[[0. 0.]
 [0. 0.]]


#### `arange`
The NumPy equivalent of Python's `range`, but it returns an `ndarray`.

In [17]:
print(f"A range from 0 to 14: {np.arange(15)}")

A range from 0 to 14: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## 1.2.3 "Like" Functions

These functions create a new array with the same shape and dtype as an existing one.

#### `ones_like`
Creates an array of ones with the same shape and dtype as the given array.

In [18]:
base_arr = np.array([[1, 2], [3, 4]])
print(f"An array of ones like base_arr:\n{np.ones_like(base_arr)}")

An array of ones like base_arr:
[[1 1]
 [1 1]]


## 1.2.4 Identity and Diagonal Arrays

#### `identity`
Creates a square identity matrix (NxN) with `1`s on the main diagonal.

In [19]:
print(f"A 3x3 identity matrix:\n{np.identity(3)}")

A 3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### `eye`
Similar to `identity`, but can create non-square matrices (MxN) and allows shifting the diagonal with `k`.

In [20]:
print(f"A 3x5 matrix with diagonal shifted by 1:\n{np.eye(3, 5, k=1)}")


A 3x5 matrix with diagonal shifted by 1:
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
