# 1.2 Creating ndarrays

In [11]:
import numpy as np

## 1.2.1 From Existing Data

### `np.array`
The main way to create an array is with `np.array`, which converts sequence-like objects (like lists) into an `ndarray`.

In [12]:
# From a simple list
data1 = [6, 7.5, 8, 8, 0, 1]
arr1 = np.array(data1)
print(f"1D Array: {arr1}")

# From a list of lists
data2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(data2)
print(f"2D Array:\\n{arr2}")

1D Array: [6.  7.5 8.  8.  0.  1. ]
2D Array:\n[[1 2 3]
 [4 5 6]]


### `np.asarray`
This function works like `np.array`, but with a key difference: if the input is already a NumPy array, `asarray` does **not** create a copy, making it more efficient.

In [13]:
# arr2 is already an ndarray
arr3 = np.asarray(arr2)

# arr3 and arr2 refer to the same object
print(f"arr3 is arr2: {arr3 is arr2}")

arr3 is arr2: True


## 1.2.2 Array Attributes

As we create arrays, NumPy assigns attributes that describe their structure.

In [14]:
# ndim: number of dimensions
print(f"arr2 dimensions: {arr2.ndim}")

# shape: size of each dimension
print(f"arr2 shape: {arr2.shape}")

# dtype: data type of the elements
print(f"arr2 dtype: {arr2.dtype}")

arr2 dimensions: 2
arr2 shape: (2, 3)
arr2 dtype: int64


## 1.2.3 Creating Arrays from Scratch

NumPy provides functions to create arrays without needing an existing Python object. These are highly efficient.

### `zeros` and `ones`
Create arrays of a given shape filled with `0`s or `1`s.

In [15]:
# 1D array of zeros
print(np.zeros(10))

# 2D array of ones
print(np.ones((3, 5)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### `empty`
Creates an array of a given shape without initializing its values. This is the fastest option, but the array will contain uninitialized "garbage" values.

In [16]:
# An uninitialized 2x3 array
print(np.empty((2, 3)))

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


### `arange`
The NumPy equivalent of Python's `range`, but it returns an `ndarray`.

In [17]:
print(np.arange(15))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## 1.2.4 "Like" Functions

These functions create a new array with the same **shape and dtype** as an existing one.

In [18]:
# Create a 2x3 array
base_arr = np.array([[1, 2, 3], [4, 5, 6]])

# Create an array of ones with the same shape as base_arr
ones_arr = np.ones_like(base_arr)
print(ones_arr)

[[1 1 1]
 [1 1 1]]


## 1.2.5 Identity and Diagonal Arrays

### `identity`
Creates a square identity matrix (NxN) with `1`s on the main diagonal.

In [19]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### `eye`
Similar to `identity`, but can create non-square matrices (MxN) and allows shifting the diagonal with the `k` parameter.

In [20]:
# A 3x5 matrix with 1s on the first upper diagonal (k=1)
print(np.eye(3, 5, k=1))


[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
