# 1.3 tipos de dados para ndarrays

In [1]:
import numpy as np
from numpy import dtype

O topo de dado ou `dtype` e um objeto espacial que contem informacoes (ou metadados ,dados sobre dados) das quais o ndarray precisa interpretar uma parte da memoria como um tipo de dado especifico:

In [4]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

arr2 = np.array([1, 2, 3], dtype=np.int64)

In [5]:
arr1.dtype

dtype('float64')

In [6]:
arr2.dtype

dtype('int64')

Os tipos de dados sao fontes flexiveis do Numpy para interpretacao como dados vindos de outro sistema. Quase sempre eles fornecem diretamente para uma representacao subjacente no disco ou na memoria, o que possibilita ler grandes fluxos de dados binarios em disco concentrandose com o codigo escrito em uma linguagem de baixo nivel como `C` ou `FORTRAN`. Os tipos de dados numericos sao nomeados da mesma forma: o nome do tipo floatou int, seguindo de um numero seguindo de um indicdo por elemento ou `bits`por elemento. Um Valor ponto flutuanmte de tupla precisao padrao (que e usando internamente mo objeto float Python) ocupa 8 `bits` ou 64 `bits`. Logo esse tipo de dado e conhecido no Numpy como `float64`.

## 1.3.1 Tipos de dados

| Tipo                      | Código do tipo     | Descrição                                                                                 |
|---------------------------|--------------------|-------------------------------------------------------------------------------------------|
| int8, uint8              | i1, u1             | Tipos inteiros de 8 bits (1 byte) com e sem sinal.                                       |
| int16, uint16            | i2, u2             | Tipos inteiros de 16 bits com e sem sinal.                                               |
| int32, uint32            | i4, u4             | Tipos inteiros de 32 bits com e sem sinal.                                               |
| int64, uint64            | i8, u8             | Tipos inteiros de 64 bits com e sem sinal.                                               |
| float16                  | f2                 | Ponto flutuante com precisão metade da precisão.                                         |
| float32                  | f4 ou f            | Ponto flutuante padrão de precisão simples; compatível com o float do C.                 |
| float64                  | f8 ou d            | Ponto flutuante padrão de dupla precisão; compatível com o float do Python.              |
| float128                 | f16 ou g           | Ponto flutuante de precisão estendida.                                                   |
| complex64, complex128,   | c8, c16, c32       | Números complexos representados por dois floats de 32, 64 ou 128 bits, respectivamente.  |
| complex256               |                    |                                                                                           |
| bool                     | ?                  | Tipo booleano que armazena os valores True e False.                                      |
| object                   | O                  | Tipo de objeto Python; um valor poderia ser qualquer objeto Python.                      |
| string_                  | S                  | Tipo string ASCII de tamanho fixo (1 byte por caractere); por exemplo, 'S10'.           |
| unicode_                 | U                  | Tipo Unicode de tamanho fixo; mesma semântica de string_ (por exemplo, 'U10').          |


## 1.3.2 Criando um arra de um tipo especifico

Voce pode converter ou executar o casting de um array de um array de um tipo de daods para outra de maneira explicita usadno o metodo `astypy` do ndarray

In [8]:
arr = np.array([1, 2, 3, 4])

In [9]:
arr.dtype

dtype('int64')

In [10]:
float_arr = arr.astype('float64')

In [11]:
float_arr.dtype

dtype('float64')

In [12]:
print(float_arr)

[1. 2. 3. 4.]


Nesse exemplo fisemos um arrai de valores inteiros e depois mudasmos para float mas se fizermos o processo inverso os valores decimais ficaram truncadas

In [13]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [14]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [15]:
arr.astype('int64')

array([ 3, -1, -2,  0, 12, 10])

## 1.3.3 Convertendo valores numericos que sao strings para valores numericos

In [20]:
numeric_strings = np.array(["1.25" ,"-9.6" ,"46"], dtype = np.str_ )

In [21]:
numeric_strings

array(['1.25', '-9.6', '46'], dtype='<U4')

In [22]:
numeric_strings.astype("float")

array([ 1.25, -9.6 , 46.  ])