# 1.4 Arithmetic with NumPy Arrays

In [11]:
import numpy as np

Arrays allow you to perform batch operations on data without writing `for` loops. This is called **vectorization**.

In [12]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[2., 2., 2.], [3., 3., 3.]])
print(f"arr1:\n{arr1}")
print(f"arr2:\n{arr2}")

arr1:
[[1. 2. 3.]
 [4. 5. 6.]]
arr2:
[[2. 2. 2.]
 [3. 3. 3.]]


## 1.4.1 Element-Wise Operations

Any arithmetic operation between arrays of the same shape is applied element-wise.

#### Multiplication

In [13]:
print(f"arr1 * arr2:\n{arr1 * arr2}")

arr1 * arr2:
[[ 2.  4.  6.]
 [12. 15. 18.]]


#### Subtraction

In [14]:
print(f"arr1 - arr2:\n{arr1 - arr2}")

arr1 - arr2:
[[-1.  0.  1.]
 [ 1.  2.  3.]]


#### Addition

In [15]:
print(f"arr1 + arr2:\n{arr1 + arr2}")

arr1 + arr2:
[[3. 4. 5.]
 [7. 8. 9.]]


#### Division

In [16]:
print(f"arr1 / arr2:\n{arr1 / arr2}")

arr1 / arr2:
[[0.5        1.         1.5       ]
 [1.33333333 1.66666667 2.        ]]


## 1.4.2 Scalar Operations

Operations with a scalar are applied to every element in the array. This is a feature known as **broadcasting**.

#### Division with a Scalar

In [17]:
print(f"1 / arr1:\n{1 / arr1}")

1 / arr1:
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


#### Power

In [18]:
print(f"arr1 squared:\n{arr1 ** 2}")

arr1 squared:
[[ 1.  4.  9.]
 [16. 25. 36.]]


## 1.4.3 Comparisons

Comparisons between arrays yield a boolean array.

In [19]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(f"arr2 > arr1:\n{arr2 > arr1}")


arr2 > arr1:
[[False  True False]
 [ True False  True]]
