# 1.4 Arithmetic with NumPy Arrays

In [1]:
import numpy as np

Arrays allow you to perform batch operations on data without writing `for` loops. NumPy users call this **vectorization**. Any arithmetic operation between arrays of the same size is applied element-wise.

In [2]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(f"Original array:\n{arr}")

Original array:
[[1. 2. 3.]
 [4. 5. 6.]]


## 1.4.1 Element-Wise Operations

When you perform an operation between two arrays of the same shape, the operation is applied to each corresponding pair of elements.

### 1.4.1.1 Multiplication

In [3]:
print(f"Multiplication:\n{arr * arr}")

Multiplication:
[[ 1.  4.  9.]
 [16. 25. 36.]]


### 1.4.1.2 Subtraction

In [4]:
print(f"Subtraction:\n{arr - arr}")

Subtraction:
[[0. 0. 0.]
 [0. 0. 0.]]


### 1.4.1.3 Addition

In [5]:
print(f"Addition:\n{arr + arr}")

Addition:
[[ 2.  4.  6.]
 [ 8. 10. 12.]]


### 1.4.1.4 Division

In [6]:
print(f"Division:\n{arr / arr}")

Division:
[[1. 1. 1.]
 [1. 1. 1.]]


## 1.4.2 Scalar Operations

You can also perform arithmetic between an array and a scalar (a single number). The scalar is applied to every element in the array. This is a feature known as **broadcasting**.

### 1.4.2.1 Division with a Scalar

In [7]:
print(f"1 / arr:\n{1 / arr}")

1 / arr:
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


### 1.4.2.2 Power

In [8]:
print(f"arr squared:\n{arr ** 2}")

arr squared:
[[ 1.  4.  9.]
 [16. 25. 36.]]


## 1.4.3 Comparisons

Comparisons between arrays of the same size yield a boolean array, where each element is the result of the comparison between the corresponding elements.

In [9]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(f"Second array:\n{arr2}")

Second array:
[[ 0.  4.  1.]
 [ 7.  2. 12.]]


In [10]:
comparison = arr2 > arr
print(f"Comparison (arr2 > arr):\n{comparison}")


Comparison (arr2 > arr):
[[False  True False]
 [ True False  True]]
