# 1.5 Basic Indexing and Slicing

In [1]:
import numpy as np

NumPy array indexing is a rich topic, as there are many ways you may want to select a subset of your data or individual elements.

## 1.5.1 1D Arrays

One-dimensional arrays are simple; on the surface, they act similarly to Python lists.

In [2]:
arr = np.arange(10)
print(f"Original array: {arr}")

Original array: [0 1 2 3 4 5 6 7 8 9]


In [3]:
# Access an element by its index
print(f"Element at index 5: {arr[5]}")

Element at index 5: 5


In [4]:
# Access a slice of elements
print(f"Elements from index 5 to 8: {arr[5:8]}")

Elements from index 5 to 8: [5 6 7]


### The "No-Copy" View

A crucial difference from Python lists is that array slices are **views** on the original array. This means the data is **not copied**, and any modifications to the view will be reflected in the source array.

In [5]:
# Create a slice
arr_slice = arr[5:8]
print(f"Original slice: {arr_slice}")

# Modify an element in the slice
arr_slice[1] = 12345
print(f"Modified slice: {arr_slice}")

# The original array is changed
print(f"Original array after modification: {arr}")

Original slice: [5 6 7]
Modified slice: [    5 12345     7]
Original array after modification: [    0     1     2     3     4     5 12345     7     8     9]


This design choice was made for performance and memory efficiency, especially with very large arrays. If you want a **copy** of a slice instead of a view, you must explicitly copy the array.

In [6]:
arr_slice_copy = arr[5:8].copy()
arr_slice_copy[1] = 9999
print(f"Original array is unchanged: {arr}")
print(f"Copy is changed: {arr_slice_copy}")

Original array is unchanged: [    0     1     2     3     4     5 12345     7     8     9]
Copy is changed: [   5 9999    7]


## 1.5.2 2D Arrays

With multidimensional arrays, you have more options. In a 2D array, the elements at each index are one-dimensional arrays.

In [7]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"2D Array:\\n{arr2d}")

2D Array:\n[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# Accessing the third row (index 2)
print(f"Row at index 2: {arr2d[2]}")

Row at index 2: [7 8 9]


You can access individual elements by passing a comma-separated list of indices.

In [9]:
# These two methods are equivalent
print(f"Element at (0, 2): {arr2d[0][2]}")
print(f"Element at (0, 2) with comma-separated index: {arr2d[0, 2]}")

Element at (0, 2): 3
Element at (0, 2) with comma-separated index: 3


Think of axis 0 as the "rows" and axis 1 as the "columns".

| Axis 0 \\ Axis 1 | 0 | 1 | 2 |
|---|---|---|---|
| 0 | (0, 0) | (0, 1) | (0, 2) |
| 1 | (1, 0) | (1, 1) | (1, 2) |
| 2 | (2, 0) | (2, 1) | (2, 2) |

## 1.5.3 3D Arrays and Higher Dimensions

In multidimensional arrays, if you omit later indices, the returned object will be a lower-dimensional `ndarray`.

In [10]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f"3D Array shape: {arr3d.shape}")
print(f"3D Array:\\n{arr3d}")

3D Array shape: (2, 2, 3)
3D Array:\n[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
# Indexing with a single value returns a 2D array
arr3d_slice = arr3d[0]
print(f"Slice shape: {arr3d_slice.shape}")
print(f"Slice:\\n{arr3d_slice}")

Slice shape: (2, 3)
Slice:\n[[1 2 3]
 [4 5 6]]


In [12]:
# Indexing with two values returns a 1D array
arr3d_slice_2 = arr3d[0, 1]
print(f"Slice shape: {arr3d_slice_2.shape}")
print(f"Slice: {arr3d_slice_2}")


Slice shape: (3,)
Slice: [4 5 6]
