# 1.4 Aritimetica com o NUmpy

In [3]:
import numpy as np

OS arrays sao importantes porque permitem expressar operacoes em lote como dados sem ser preciso escrevre nenhum lote `for`. Os usuarios de Numpy chamam isso de vetorizacao. Qualquer operacao artitimetica entre arrays de mesmo tamanho e aplicada a todos os elementos

In [5]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [6]:
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


## 1.4.1 Multiplicacao

In [8]:
print(arr * arr)

[[ 1.  4.  9.]
 [16. 25. 36.]]


## 1.4.2 subtracao

In [10]:
print(arr - arr)

[[0. 0. 0.]
 [0. 0. 0.]]


## 1.4.2 soma

In [11]:
print(arr + arr)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]


## 1.4.2 divisao

In [12]:
print(arr / arr)

[[1. 1. 1.]
 [1. 1. 1.]]


## 1.4.3 Operacaoes aritimeticas escalares

In [14]:
print(1 / arr)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [16]:
print(arr ** 2)

[[ 1.  4.  9.]
 [16. 25. 36.]]


## 1.4.3 comparacoes entre arrays

In [17]:
arr2 = np.array(([[0., 4., 1.], [7., 2., 12.]]))

In [18]:
print(arr2)

[[ 0.  4.  1.]
 [ 7.  2. 12.]]


In [20]:
print(arr2 > arr)

[[False  True False]
 [ True False  True]]
