# 1.5 Basic Indexing and Slicing

In [1]:
import numpy as np

## 1.5.1 Indexing and Slicing 1D Arrays

One-dimensional arrays behave similarly to Python lists.

In [ ]:
arr = np.arange(10)
print(f"Original array: {arr}")

#### Indexing
Access a single element by its index.

In [3]:
print(f"Element at index 5: {arr[5]}")

Element at index 5: 5


#### Slicing
Access a range of elements.

In [ ]:
print(f"Elements from index 5 to 8: {arr[5:8]}")

### The "No-Copy" View

A crucial difference from Python lists is that array slices are **views** on the original array. This means the data is **not copied**, and any modifications to the view will be reflected in the source array.

In [ ]:
# Create a slice
arr_slice = arr[5:8]
arr_slice[1] = 12345
print(f"Original array after modification: {arr}")

To get a copy of a slice, you must use the `.copy()` method.

In [ ]:
arr_slice_copy = arr[5:8].copy()
arr_slice_copy[1] = 9999
print(f"Original array is unchanged: {arr}")
print(f"Copy is changed: {arr_slice_copy}")

## 1.5.2 Indexing and Slicing 2D Arrays

In [7]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"2D Array:\n{arr2d}")

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Accessing Rows
Indexing with a single integer accesses a whole row.

In [ ]:
print(f"Row at index 2: {arr2d[2]}")

#### Accessing Individual Elements
You can access individual elements by passing a comma-separated list of indices.

In [ ]:
print(f"Element at (0, 2): {arr2d[0, 2]}")

## 1.5.3 Indexing and Slicing 3D Arrays

In multidimensional arrays, if you omit later indices, the returned object will be a lower-dimensional `ndarray`.

In [10]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f"3D Array:\n{arr3d}")

3D Array shape: (2, 2, 3)
3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### Accessing a 2D slice
Indexing with a single value returns a 2D array.

In [12]:
arr3d_slice = arr3d[0]
print(f"2D Slice:\n{arr3d_slice}")

Slice shape: (3,)
Slice: [4 5 6]


#### Accessing a 1D slice
Indexing with two values returns a 1D array.

In [ ]:
arr3d_slice_2 = arr3d[0, 1]
print(f"1D Slice: {arr3d_slice_2}")
