# 1.4 Indexaçao e fatiamrnto basico

In [1]:
import numpy as np

A indexaçao de arrays no Numpy e um topico muito extenço, ja que exixtem muitas matrias de subconjuntos dos dados ou elementos individuais.  Os arrays unidimencionais sao simples superficialmente eles se comportam de modo semelhante a listas do Python

## 1.5.1 Arrays unidimencionais

In [4]:
arr = np.arange(10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[5]

np.int64(5)

In [8]:
arr[5:8]

array([5, 6, 7])

In [9]:
arr[5:8] = 12

In [10]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

Como voce pode ver se atribuirmos um valor escalar a uma fatia como em `arr[5:8] = 12`,  ele sera propagado para todas as seleçoes

Para dar um exmplo disso primeiro vamos criar primeiro uma fatia arr:

In [11]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

Agora quando eu alterar valores no `arr_slice`,  as modificaçoes se refleten no array original `arr`

In [12]:
arr_slice[1] = 1234

In [13]:
arr_slice

array([  12, 1234,   12])

In [14]:
arr

array([   0,    1,    2,    3,    4,   12, 1234,   12,    8,    9])

A fatia vazia `[:]` faz atribuiçoes a todos os valores em um array:

In [15]:
arr_slice[:] = 64

In [16]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

Se voce e iniciado no Numpy,  pode achar estranho,  primcipalmente se tiver usando outra linguagem de programacao de arrays que copiam dados mais avidamente.  Ja que o Numpy foi projetado para poder trabalhar com arrays muito grandes,  podemos prever ocorencia de problemas de desempenho e memoria sele ele sempre insistisse em copiar os dados

## 1.5.1 Arrays de mais dimencoes

Como arrays de mais dimencoes temos uma variedade maior de opcoes. Em um array bidimencional, os elementos de cada incice nao sao mais escalares e sim arrays unidimencionais

In [17]:
arr2d = np. array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [19]:
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
arr2d[2]

array([7, 8, 9])

Logo os elementos pode ser acessados recurcivamente.  No emtanto isso da um pouco mais de trabalho de modo que seria melhor voce passar uma lista de indices separados por virgulas, para selecionar elementos individuais. As abordsagens a seguir sao estao equivalentes

In [21]:
arr2d[0][2]

np.int64(3)

In [22]:
arr2d[0,2]

np.int64(3)

Comsultando a figura a seguir para ver uma ilustracao da indexacao em uma array bidimencional.  Pensar no eixo 0 como as "linhas” e no eixo 1 como as colinas dado array pode ajudar

| Eixo 0 \\ Eixo 1 | 0   | 1   | 2   |
|------------------|-----|-----|-----|
| 0                | 0,0 | 0,1 | 0,2 |
| 1                | 1,0 | 1,1 | 1,2 |
| 2                | 2,0 | 2,1 | 2,2 |


Em arrays multidimencionais, se voce omitir os indices finais,  o objeto retornado sera um ndarray de menos dimensoes compostos de todos od dados nas dimensoes mas altas. Logo no array 2x2x3 arr3d

In [28]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [29]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

arr3d[0] e um arr array 2x3

In [32]:
print(arr3d[0])

[[1 2 3]
 [4 5 6]]


Tanto valores escalares quanto arrays podem ser etribuidos a arr3d[0

In [33]:
old_values = arr3d[0].copy()

In [35]:
print(old_values)

[[1 2 3]
 [4 5 6]]


In [36]:
arr3d[0] = 42

In [37]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [38]:
arr3d[0] = old_values

In [39]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

a mesma forma,  arr3d[1,0] fornece todos os valores cujos indices comecem com (1, 0), formando um array unidimencional

In [40]:
arr3d[1, 0]

array([7, 8, 9])

Essa expressao e como se tivesemos feito a indexacao em duas etapas:

In [41]:
x = arr3d[1]

In [43]:
print(x)

[[ 7  8  9]
 [10 11 12]]


In [44]:
x[0]

array([7, 8, 9])

Observe que em todos esses casos em que subsecoes do array foram selecionados os arrays retornados sao cisualisacoes