# 1.6 Slicing ndarrays

In [1]:
import numpy as np

Like one-dimensional objects such as Python lists, ndarrays can be sliced with the familiar syntax.

In [2]:
arr = np.arange(10)
print(f"Original array: {arr}")

Original array: [0 1 2 3 4 5 6 7 8 9]


In [3]:
# A slice of the first 6 elements
print(f"Slice [1:6]: {arr[1:6]}")

Slice [1:6]: [1 2 3 4 5]


## 1.6.1 2D Array Slicing

With a 2D array, slicing is a bit different. Slicing along axis 0 (the first axis) selects a range of rows.

In [4]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"2D Array:\\n{arr2d}")

2D Array:\n[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Select the first two rows
print(f"First two rows:\\n{arr2d[:2]}")

First two rows:\n[[1 2 3]
 [4 5 6]]


You can pass multiple slices, just like you can pass multiple indexes.

In [6]:
# Select the first two rows and columns from index 1 onward
print(f"Slice [:2, 1:]:\\n{arr2d[:2, 1:]}")

Slice [:2, 1:]:\n[[2 3]
 [5 6]]


## 1.6.2 Mixing Slicing and Indexing

When you mix integer indexing and slicing, you get slices with a lower dimension.

In [7]:
# Select the second row (index 1) but only the first two columns
lower_dim_slice = arr2d[1, :2]
print(f"Lower-dimensional slice: {lower_dim_slice}")
print(f"Shape of the slice: {lower_dim_slice.shape}")

Lower-dimensional slice: [4 5]
Shape of the slice: (2,)


Similarly, you can select the third column but only from the first two rows.

In [8]:
print(f"Slice [:2, 2]: {arr2d[:2, 2]}")

Slice [:2, 2]: [3 6]


Using a colon by itself means "take the entire axis."

In [9]:
# Select all rows, but only the first column
print(f"Slice [:, :1]:\\n{arr2d[:, :1]}")

Slice [:, :1]:\n[[1]
 [4]
 [7]]


Assigning to a slice expression assigns to the entire selection.

In [10]:
arr2d[:2, 1:] = 0
print(f"Modified array:\\n{arr2d}")

Modified array:\n[[1 0 0]
 [4 0 0]
 [7 8 9]]


<style>
    .slice-table-container {
        font-family: "Segoe UI", Arial, sans-serif;
        margin: 20px auto;
        max-width: 800px;
        border: 1px solid #e1e4e8;
        border-radius: 6px;
        box-shadow: 0 4px 8px rgba(0,0,0,0.05);
        overflow: hidden;
    }
    .slice-table-container h3 {
        color: #24292e;
        background-color: #f6f8fa;
        padding: 15px 20px;
        margin: 0;
        border-bottom: 1px solid #e1e4e8;
    }
    .slice-table {
        width: 100%;
        border-collapse: collapse;
    }
    .slice-table th, .slice-table td {
        padding: 15px 20px;
        text-align: left;
        border-bottom: 1px solid #e1e4e8;
    }
    .slice-table th {
        font-weight: 600;
        background-color: #f6f8fa;
    }
    .slice-table tbody tr:nth-child(even) {
        background-color: #f6f8fa;
    }
    .slice-table tbody tr:hover {
        background-color: #f0f8ff;
    }
    .slice-table code {
        background-color: #eef;
        padding: 3px 6px;
        border-radius: 4px;
        font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, Courier, monospace;
    }
    .slice-table .shape {
        font-weight: bold;
        text-align: center;
    }
    .slice-table .shape-dim {
        font-size: 0.9em;
        color: #586069;
    }
    .slice-grid {
        display: inline-block;
        border-collapse: collapse;
    }
    .slice-grid td {
        width: 18px;
        height: 18px;
        padding: 0;
        text-align: center;
        border: 1px solid #d1d5da;
    }
    .selected { background-color: #3498db; }
    .unselected { background-color: #ecf0f1; }
    .footer-note {
        font-size: 0.9em;
        color: #586069;
        padding: 15px 20px;
        background-color: #f6f8fa;
        font-style: italic;
    }
</style>

<div class="slice-table-container">
    <h3>2D Array Slicing Examples</h3>
    <table class="slice-table">
        <thead>
            <tr>
                <th style="text-align: center;">Visual</th>
                <th>Expression</th>
                <th style="text-align: center;">Resulting Shape</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <table class="slice-grid">
                        <tr><td class="unselected"></td><td class="selected"></td><td class="selected"></td></tr>
                        <tr><td class="unselected"></td><td class="selected"></td><td class="selected"></td></tr>
                        <tr><td class="unselected"></td><td class="unselected"></td><td class="unselected"></td></tr>
                    </table>
                </td>
                <td><code>arr[:2, 1:]</code></td>
                <td class="shape">(2, 2) <span class="shape-dim">(2D)</span></td>
            </tr>
            <tr>
                <td>
                    <table class="slice-grid">
                        <tr><td class="unselected"></td><td class="unselected"></td><td class="unselected"></td></tr>
                        <tr><td class="unselected"></td><td class="unselected"></td><td class="unselected"></td></tr>
                        <tr><td class="selected"></td><td class="selected"></td><td class="selected"></td></tr>
                    </table>
                </td>
                <td>
                    <code>arr[2]</code> or <code>arr[2, :]</code><br>
                    <code>arr[2:, :]</code>
                </td>
                <td class="shape">
                    (3,) <span class="shape-dim">(1D)</span><br>
                    (1, 3) <span class="shape-dim">(2D)</span>
                </td>
            </tr>
            <tr>
                <td>
                    <table class="slice-grid">
                        <tr><td class="selected"></td><td class="selected"></td><td class="unselected"></td></tr>
                        <tr><td class="selected"></td><td class="selected"></td><td class="unselected"></td></tr>
                        <tr><td class="selected"></td><td class="selected"></td><td class="unselected"></td></tr>
                    </table>
                </td>
                <td><code>arr[:, :2]</code></td>
                <td class="shape">(3, 2) <span class="shape-dim">(2D)</span></td>
            </tr>
            <tr>
                <td>
                    <table class="slice-grid">
                        <tr><td class="unselected"></td><td class="unselected"></td><td class="unselected"></td></tr>
                        <tr><td class="selected"></td><td class="selected"></td><td class="unselected"></td></tr>
                        <tr><td class="unselected"></td><td class="unselected"></td><td class="unselected"></td></tr>
                    </table>
                </td>
                <td>
                    <code>arr[1, :2]</code><br>
                    <code>arr[1:2, :2]</code>
                </td>
                <td class="shape">
                    (2,) <span class="shape-dim">(1D)</span><br>
                    (1, 2) <span class="shape-dim">(2D)</span>
                </td>
            </tr>
        </tbody>
    </table>
    <p class="footer-note">
        Key takeaway: Integer indexing reduces dimensions, while slicing preserves them.
    </p>
</div>
