# 1.6 Indexacao de fatias

In [46]:
import numpy as np

Assim como os objetos unidimencionais, como listas Python, os ndarrays podem ser fatiados como sintax conhecida a seguir

In [77]:
arr = np. array([0, 1, 2, 3, 4, 64, 64, 64, 8, 9])

In [78]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [79]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

Considerando o arrya bidimencional anterior, arr2d.  O Fatiamneto desse array e um pouco drierente

In [80]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [82]:
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [84]:
print(arr2d[:2])

[[1 2 3]
 [4 5 6]]


Como voce pode ver foi fatiado ao longo do eixo 0, que e o orimeiro eixo.  Uma fatia postanto,  seleciona um intervalo de elementos ao longo de um eixo.  Ler a expressao `arr2d[:2]` como "seleciona as duas primeiras linhas de arr2d” pode ajudar.

Podemos passar varias fatias do mesmo modo que podemos passar varios indices

In [87]:
print(arr2d[:2, 1:])

[[2 3]
 [5 6]]


Em um fatiamneto como esse sempre obtemos visualizacoes do array com o mesmo numero de dimencoes.  Combinando indices inteiros e fatias, podemos obter fatias com menos dimencoes

Por exmplo, posso selecionar a segunda linha mas so as duas primeiras colunas,  desta forma:

In [88]:
lower_dim_slice = arr2d[1, : 2]

In [89]:
lower_dim_slice

array([4, 5])

Aqui apesar de que `arr2d` seja bidimencional,  `lower_dim_slice` e unidimencional e tem a forma de uma tupla com tamanho de um unico eixo:

In [91]:
lower_dim_slice.shape

(2,)

de manira semelhante posso selecionar a terceira coluna mas so as duas primeiras linhas, como discrito a seguir

In [92]:
arr2d[:2, 2]

array([3, 6])

Comsulte a figura a seguir oar5a ver uma ilustracao.  E bom ressaltar que os dois pontos sozinhos siginificao usar o eixo inteiro logho, voce pode fatiar apenas eixos com mais dimencoes fazendo o seguinte:

In [94]:
print(arr2d[:, :1])

[[1]
 [4]
 [7]]


E claro que fazer uma atribuicao para uma expressao de fatia faz a atribuicao para toda a selecao

In [95]:
arr2d[:2, 1:] = 0

In [97]:
print(arr2d)

[[1 0 0]
 [4 0 0]
 [7 8 9]]


<div style="font-family: sans-serif; max-width: 800px;">
    <h3 style="color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px;">
        Fatiamento de Arrays Bidimensionais (NumPy)
    </h3>
    <table style="width: 100%; border-collapse: collapse; margin-top: 15px; background-color: white;">
        <thead>
            <tr style="background-color: #f8f9fa; border-bottom: 2px solid #dee2e6;">
                <th style="padding: 12px; text-align: center;">Representação Visual</th>
                <th style="padding: 12px; text-align: left;">Expressão</th>
                <th style="padding: 12px; text-align: center;">Forma (Shape)</th>
            </tr>
        </thead>
        <tbody>
            <tr style="border-bottom: 1px solid #eee;">
                <td style="padding: 15px; text-align: center;">
                    <table style="display: inline-block; border: 1px solid #333; border-spacing: 2px;">
                        <tr><td style="width:15px; height:15px; background:#eee;"></td><td style="width:15px; height:15px; background:#3498db;"></td><td style="width:15px; height:15px; background:#3498db;"></td></tr>
                        <tr><td style="width:15px; height:15px; background:#eee;"></td><td style="width:15px; height:15px; background:#3498db;"></td><td style="width:15px; height:15px; background:#3498db;"></td></tr>
                        <tr><td style="width:15px; height:15px; background:#eee;"></td><td style="width:15px; height:15px; background:#eee;"></td><td style="width:15px; height:15px; background:#eee;"></td></tr>
                    </table>
                </td>
                <td style="padding: 15px;"><code>arr[:2, 1:]</code></td>
                <td style="padding: 15px; text-align: center; font-weight: bold;">(2, 2)</td>
            </tr>
            <tr style="border-bottom: 1px solid #eee;">
                <td style="padding: 15px; text-align: center;">
                    <table style="display: inline-block; border: 1px solid #333; border-spacing: 2px;">
                        <tr><td style="width:15px; height:15px; background:#eee;"></td><td style="width:15px; height:15px; background:#eee;"></td><td style="width:15px; height:15px; background:#eee;"></td></tr>
                        <tr><td style="width:15px; height:15px; background:#eee;"></td><td style="width:15px; height:15px; background:#eee;"></td><td style="width:15px; height:15px; background:#eee;"></td></tr>
                        <tr><td style="width:15px; height:15px; background:#3498db;"></td><td style="width:15px; height:15px; background:#3498db;"></td><td style="width:15px; height:15px; background:#3498db;"></td></tr>
                    </table>
                </td>
                <td style="padding: 15px;">
                    <code>arr[2]</code><br>
                    <code>arr[2, :]</code><br>
                    <code>arr[2:, :]</code>
                </td>
                <td style="padding: 15px; text-align: center;">
                    <code>(3,)</code><br>
                    <code>(3,)</code><br>
                    <code>(1, 3)</code>
                </td>
            </tr>
            <tr style="border-bottom: 1px solid #eee;">
                <td style="padding: 15px; text-align: center;">
                    <table style="display: inline-block; border: 1px solid #333; border-spacing: 2px;">
                        <tr><td style="width:15px; height:15px; background:#3498db;"></td><td style="width:15px; height:15px; background:#3498db;"></td><td style="width:15px; height:15px; background:#eee;"></td></tr>
                        <tr><td style="width:15px; height:15px; background:#3498db;"></td><td style="width:15px; height:15px; background:#3498db;"></td><td style="width:15px; height:15px; background:#eee;"></td></tr>
                        <tr><td style="width:15px; height:15px; background:#3498db;"></td><td style="width:15px; height:15px; background:#3498db;"></td><td style="width:15px; height:15px; background:#eee;"></td></tr>
                    </table>
                </td>
                <td style="padding: 15px;"><code>arr[:, :2]</code></td>
                <td style="padding: 15px; text-align: center; font-weight: bold;">(3, 2)</td>
            </tr>
            <tr>
                <td style="padding: 15px; text-align: center;">
                    <table style="display: inline-block; border: 1px solid #333; border-spacing: 2px;">
                        <tr><td style="width:15px; height:15px; background:#eee;"></td><td style="width:15px; height:15px; background:#eee;"></td><td style="width:15px; height:15px; background:#eee;"></td></tr>
                        <tr><td style="width:15px; height:15px; background:#3498db;"></td><td style="width:15px; height:15px; background:#3498db;"></td><td style="width:15px; height:15px; background:#eee;"></td></tr>
                        <tr><td style="width:15px; height:15px; background:#eee;"></td><td style="width:15px; height:15px; background:#eee;"></td><td style="width:15px; height:15px; background:#eee;"></td></tr>
                    </table>
                </td>
                <td style="padding: 15px;">
                    <code>arr[1, :2]</code><br>
                    <code>arr[1:2, :2]</code>
                </td>
                <td style="padding: 15px; text-align: center;">
                    <code>(2,)</code><br>
                    <code>(1, 2)</code>
                </td>
            </tr>
        </tbody>
    </table>
    <p style="font-size: 0.9em; color: #7f8c8d; margin-top: 10px; font-style: italic;">
        Obs: O fatiamento (slicing) mantém a dimensionalidade, enquanto a indexação com inteiros reduz o número de dimensões.
    </p>
</div>
