# 1.6 Indexacao booleana

In [100]:
import numpy as np

Considerando um exemplo no qual temos alguns dados em um array e um array de nomes com duplicadas

In [101]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob',  'Joe', 'Will',  "Joe" ])

['Bob' 'Joe' 'Will' 'Bob' 'Joe' 'Will' 'Joe']


In [102]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Joe', 'Will', 'Joe'], dtype='<U4')

In [103]:
data = np.array([[4, 7], [0,2], [-5, 6], [0,0], [1, 2], [-12, -4], [3, 4]])

In [105]:
print(data)

[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]


Suponhamos que cada nome corresponde uma linha de um array data e quisermos selecionar todas as linhas cujo nome correespomdemte foss `Bob`.  com as operacoes aritimedicas,  as comparacoes (como com ==) com arrays tambem sao vetorisaodos.  Logo comparar `names` com `string` "Bob” gera um array bpleano

In [106]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

Esse array booleano pode ser passado quando o array for indexado:

In [108]:
print(data[names == 'Bob'])

[[4 7]
 [0 0]]


O array boleano deve ter o mesmo tamanho do eixo de array que ele esta indexado.  Voce pode ate mesmo combinar arrays booleanos com fatias ou inteiros (ou sequancias de inteiros)

Nestes exemplos,  estou fazendo a selecao nas linhas em que `names == Bob` e tambem estou indexando as colunas

In [111]:
print(data[names == 'Bob',  1:])

[[7]
 [0]]


In [112]:
print(data[names == 'Bob',  1])

[7 0]


Para celcionar tudo exceto Bob voce pode usar `!=` ou nefar a condiccao utilisanmco `~`


In [113]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [114]:
~(names == 'Bob')

array([False,  True,  True, False,  True,  True,  True])

In [115]:
print(data[~(names == 'Bob')])

[[  0   2]
 [ -5   6]
 [  1   2]
 [-12  -4]
 [  3   4]]


O operdos `~` pode ser util quando voce quiser inverter um array booleana referencido por uma variavel:

In [116]:
cond = names == 'Bob'

In [117]:
cond

array([ True, False, False,  True, False, False, False])

In [118]:
print(data[~cond])

[[  0   2]
 [ -5   6]
 [  1   2]
 [-12  -4]
 [  3   4]]


Para selecionar dois dos tres nomes e combinar varias condicoes booleanas, use operadores aritimeticas booleanas `&` (and) e `|` (or)

In [119]:
mask = (names == 'Bob') | (names == 'Will')

In [120]:
mask

array([ True, False,  True,  True, False,  True, False])

In [122]:
print(data[mask])

[[  4   7]
 [ -5   6]
 [  0   0]
 [-12  -4]]


A selecao de dados de um array por indexacao booleana e a atribuicao do resultado a uma nova variavel sempre cria uma copia dos dados,  mesmo se o array retornado nao for aleatorio.

Obs: apavars `and` e `or` do Python nao funciona com arrays boenaos.

A definicao de valores com arrays booleanos funciona pela trensferencia de valores ou dos valores que estiverem no lado dierito para os locais em que os valores do array booleano forem `True`.  Parta configurar todos os valores negativos de `data` com 0, so precisamos fazer o seguint:

In [123]:
data[data < 0] = 0

In [125]:
print(data)

[[4 7]
 [0 2]
 [0 6]
 [0 0]
 [1 2]
 [0 0]
 [3 4]]


In [ ]:
print(data[names == 'Bob',  1:])

Voce tambem pode definir linhas e colunas inteiras usando um array booleano unidimencional

In [126]:
data[names != 'Joe'] = 7

In [128]:
print(data)

[[7 7]
 [0 2]
 [7 7]
 [7 7]
 [1 2]
 [7 7]
 [3 4]]


Como veremos posteriormente,  esses tipos de opareacoes com dados bidimencionais sao mais convenientes com pandas>