# 1.8 Fancy Indexing

In [1]:
import numpy as np

*Fancy indexing* is a term adopted by NumPy to describe indexing using integer arrays.

## 1.8.1 Indexing with Integer Arrays

Suppose we have an 8x4 array.

In [2]:
# Create an 8x4 array
arr = np.arange(32).reshape((8, 4))
print(f"Original array:\n{arr}")

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


To select a subset of the rows in a particular order, you can simply pass a list or an array of integers specifying the desired order.

In [3]:
# Select rows 4, 3, 0, and 6
print(f"Selected rows:\n{arr[[4, 3, 0, 6]]}")

Selected rows:
[[16 17 18 19]
 [12 13 14 15]
 [ 0  1  2  3]
 [24 25 26 27]]


Using negative indices selects rows from the end.

In [4]:
# Select rows -3, -5, and -7 from the end
print(f"Selected rows from the end:\n{arr[[-3, -5, -7]]}")

Selected rows from the end:
[[20 21 22 23]
 [12 13 14 15]
 [ 4  5  6  7]]


## 1.8.2 Passing Multiple Index Arrays

Passing multiple index arrays does something slightly different; it selects a 1D array of elements corresponding to each tuple of indices.

In [5]:
# Select elements at (1, 0), (5, 3), (7, 1), and (2, 2)
selected_elements = arr[[1, 5, 7, 2], [0, 3, 1, 2]]
print(f"Selected elements: {selected_elements}")

Selected elements: [ 4 23 29 10]


The result of fancy indexing with multiple index arrays is always one-dimensional.

If you want to select a rectangular region formed by a subset of rows and columns, you can do it like this:

In [6]:
# Select a block of rows and columns
block = arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]
print(f"Selected block:\n{block}")

Selected block:
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


## 1.8.3 Setting Values with Fancy Indexing

Keep in mind that fancy indexing, unlike slicing, **always copies the data** into a new array. However, when assigning values with fancy indexing, the indexed values are modified.

In [7]:
# Set the selected elements to 0
print(f"Original array:\n{arr}")
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
print(f"Modified array:\n{arr}")


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
Modified array:
[[ 0  1  2  3]
 [ 0  5  6  7]
 [ 8  9  0 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22  0]
 [24 25 26 27]
 [28  0 30 31]]
