# 1.8 Fancy Indexing

In [1]:
import numpy as np

*Fancy indexing* is a term for indexing using integer arrays.

In [ ]:
arr = np.arange(32).reshape((8, 4))
print(f"Original array:\n{arr}")

## 1.8.1 Selecting Rows

To select a subset of rows in a particular order, pass a list or array of integers.

In [ ]:
# Select rows 4, 3, 0, and 6
print(f"Selected rows:\n{arr[[4, 3, 0, 6]]}")

Using negative indices selects rows from the end.

In [ ]:
# Select rows -3, -5, and -7 from the end
print(f"Selected rows from the end:\n{arr[[-3, -5, -7]]}")

## 1.8.2 Selecting Individual Elements

Passing multiple index arrays selects a 1D array of elements corresponding to each tuple of indices.

In [ ]:
# Select elements at (1, 0), (5, 3), (7, 1), and (2, 2)
selected_elements = arr[[1, 5, 7, 2], [0, 3, 1, 2]]
print(f"Selected elements: {selected_elements}")

## 1.8.3 Selecting a Rectangular Region

To select a rectangular region, you can combine row and column selections.

In [6]:
# Select a block of rows and columns
block = arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]
print(f"Selected block:\n{block}")

Selected block:
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


## 1.8.4 Setting Values with Fancy Indexing

Fancy indexing, unlike slicing, **always copies the data** into a new array. However, you can still use it to modify the original array.

In [7]:
# Set the selected elements to 0
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
print(f"Modified array:\n{arr}")


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
Modified array:
[[ 0  1  2  3]
 [ 0  5  6  7]
 [ 8  9  0 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22  0]
 [24 25 26 27]
 [28  0 30 31]]
