# 1.9 Transposing Arrays and Swapping Axes

In [1]:
import numpy as np

Transposing is a special form of reshaping that similarly returns a **view** on the underlying data without copying anything. Arrays have the `transpose` method and also the special `T` attribute.

In [2]:
arr = np.arange(15).reshape((3, 5))
print(f"Original array (3x5):\n{arr}")

Original array (3x5):
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
# Transpose the array
print(f"Transposed array (5x3):\n{arr.T}")

Transposed array (5x3):
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


## 1.9.1 Matrix Computations

When doing matrix computations, you may use this very often. For example, when computing the inner matrix product using `np.dot`.

In [4]:
arr = np.random.standard_normal((2, 3))
print(f"Original array:\n{arr}")

Original array:
[[ 0.15933742 -0.6397164   0.36268841]
 [ 0.35160414  1.19402338 -0.4962366 ]]


In [5]:
# Compute the inner product of arr and its transpose
inner_product = np.dot(arr.T, arr)
print(f"Inner product:\n{inner_product}")

Inner product:
[[ 0.14901389  0.31789281 -0.11668901]
 [ 0.31789281  1.8349289  -0.82453583]
 [-0.11668901 -0.82453583  0.37779365]]


The `@` infix operator is another way to do matrix multiplication.

In [6]:
print(f"Inner product with @:\n{arr.T @ arr}")

Inner product with @:
[[ 0.14901389  0.31789281 -0.11668901]
 [ 0.31789281  1.8349289  -0.82453583]
 [-0.11668901 -0.82453583  0.37779365]]


## 1.9.2 Swapping Axes

Simple transposing with `.T` is a special case of swapping axes. `ndarray` has the method `swapaxes`, which takes a pair of axis numbers and switches the indicated axes to rearrange the data.

In [7]:
arr = np.arange(16).reshape((2, 2, 4))
print(f"Original 3D array (shape {arr.shape}):\n{arr}")

Original 3D array (shape (2, 2, 4)):
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [8]:
# Swap axis 0 and 1
swapped_arr = arr.swapaxes(0, 1)
print(f"Swapped array (shape {swapped_arr.shape}):\n{swapped_arr}")

Swapped array (shape (2, 2, 4)):
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


`swapaxes` similarly returns a view on the data without making a copy.
