# 1.9 Transposing Arrays and Swapping Axes

In [1]:
import numpy as np

Transposing returns a **view** of the data with the axes permuted.

## 1.9.1 Transposing with `.T`

The `.T` attribute is a special case for transposing, ideal for 2D arrays.

In [ ]:
arr = np.arange(15).reshape((3, 5))
print(f"Original array (3x5):\n{arr}")
print(f"Transposed array (5x3):\n{arr.T}")

## 1.9.2 Matrix Computations

Transposing is common in matrix computations, like calculating the inner product.

#### `np.dot`

In [ ]:
arr = np.random.standard_normal((2, 3))
inner_product = np.dot(arr.T, arr)
print(f"Inner product with np.dot:\n{inner_product}")

#### `@` operator
The `@` infix operator is a convenient way to do matrix multiplication.

In [ ]:
print(f"Inner product with @:\n{arr.T @ arr}")

## 1.9.3 Swapping Axes with `swapaxes`

For multidimensional arrays, `swapaxes` takes a pair of axis numbers and switches them. It also returns a view on the data.

In [8]:
arr = np.arange(16).reshape((2, 2, 4))
print(f"Original 3D array (shape {arr.shape}):\n{arr}")

Swapped array (shape (2, 2, 4)):
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [ ]:
# Swap axis 0 and 1
swapped_arr = arr.swapaxes(0, 1)
print(f"Swapped array (shape {swapped_arr.shape}):\n{swapped_arr}")
