# 1.6 Indexacao sofisticada

In [1]:
import numpy as np

Indexacao sofisticada (fancy index) e um termo adotado pelo numpy para descrever a indexacao como o uso de arrays de interiros.  Suponha que tivemos um array 8x4:

In [2]:
arr = np.zeros((8, 4))

In [4]:
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
for i in range(8):
    arr[i] = i

In [8]:
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


Para selecionar um subconjunto das linhas em uma ordem especifica,  basta passar uma lista ou um ndarray de inteiros especificos a ordem desejada

In [10]:
print(arr[[4, 3, 0, 6]])

[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]


Usar indices negativos seleciona as linhas a partir do final

In [12]:
print(arr[[-3, -5, -7]])

[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]


Passar arrays com varios indices produz um resultado um pouco diferente; e selecionado um array unidimencional de elementos correspondentes a cada tupla de indices

In [13]:
arr = np.arange(32).reshape((8, 4))

In [15]:
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [16]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

Para saber mais sobre a funcao resahpe consulte a pasata a parte de Numpy avancado desse repositorio.

Aqui os elementos (1, 0), (5, 3), (7, 1) e (2,2) foram selecionados. Os resultados indexacao sofisticada com um numero de arrays de inteiros equivalenete ao numero de eixo e sempre unidimencional.

O comportamento da indexacao sofisticada nesse caso e um pouco diferente do que alguns usuarios esperam, que e a regiao retangular formada pela selecao de um subconjunto das linhas e colunas da matriz.  seja siquer uma maneira de obter isso:


In [19]:
print(arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


Lembrece que a indexacao sofisticada ao contrario, ao da fatiamento, sempre copia os dados em um novo array ao atribuir o resultado a uma nova variavel. se voce atribui valores com a indexacao sofisticada,  os valores com a indexacao sofisticada os valores indexados serao modificados:

In [20]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [21]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0

In [23]:
print(arr)

[[ 0  1  2  3]
 [ 0  5  6  7]
 [ 8  9  0 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22  0]
 [24 25 26 27]
 [28  0 30 31]]
