# 2.1 Geracao de numeros pseudo aleatorios

In [73]:
import numpy as np

O modulo `numpy.random` complementa o modulo random introno do python, para a geracao aleatorias de arrays de inteiros com valores de amostras de muitos tipos de distribuicoes de probabilidade. Por exemplo voce pode obter um array 4x4 de amostras da distribuicao normal usando `numpy.random.stand_normal:`

In [74]:
sample = np.random.standard_normal(size = (4, 4))

In [75]:
print(sample)

[[-1.50973884e+00 -1.52545145e-04 -1.31731906e+00 -7.50779252e-01]
 [-9.76352378e-02  1.18219233e+00 -7.32783444e-01  5.94607566e-01]
 [-3.92448057e-01 -9.75170891e-01  3.26493148e-01  1.66974224e+00]
 [-3.01090890e-01  1.58654759e-01  3.87199018e-02  5.50557840e-01]]


Em contrapartida, o modulo `random` interno do Python so obtem a amostra de um valor da cada vez. Como voce pode ver nesse benchmark, `numpy.random` e acima de uma ordem de grandeza mais rapido para a geracao de amostras muito grandes.

In [76]:
from random import normalvariate

In [77]:
N = 1_000_000

In [78]:
%time sample = [normalvariate(0,1) for _ in range(N)]

CPU times: user 360 ms, sys: 9.75 ms, total: 370 ms
Wall time: 370 ms


In [79]:
%time np.random.standard_normal(N)

CPU times: user 15.2 ms, sys: 1.35 ms, total: 16.5 ms
Wall time: 15.6 ms


array([-1.14732424,  0.18204685,  0.10829219, ..., -0.28793171,
        0.81089419, -0.27828919], shape=(1000000,))

Esses numeros nao sao realmenrte aleatorios (sao pseudo aleatorios): eles sao criados por um gerador de numeros aleatorios configuravel que define deterministucamente que valores sao criados. Funoes como `np.random.standard_normal` usam o gerador de numeros aleatorios padram `numpy.random` mas o codigo pode ser configurado para usar um gerados explicito:

In [80]:
rng = np.random.default_rng(seed = 12345)

In [81]:
data = rng.standard_normal((2,3))

In [82]:
print(data)

[[-1.42382504  1.26372846 -0.87066174]
 [-0.25917323 -0.07534331 -0.74088465]]


O argumento `seed` e que determina o estado inicial do gerador e o estado muda sempre que o objeto `rng` e usado para gerar os dados. o objetivo gerdor `rng` tambem fica isolado de qualquer outrp que possa usar o modulo `numpy.random` fica isolado de qualquer outro codigo que possa usar o modulo `numpy.random`

In [83]:
type(rng)

numpy.random._generator.Generator

A seguir outros metodos disponiveis para objetos de gerador aleatorios como `rng`.

In [84]:
rng = np.random.default_rng(12345)
data = rng.permutation(10)

In [85]:
data

array([4, 8, 1, 3, 7, 9, 6, 0, 2, 5])

In [86]:
arr = np.arange(10)
print(arr)
rng.shuffle(arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[0 9 3 5 2 6 1 8 7 4]


In [87]:
rng.uniform(low=0.0, high=10.0, size=None)

8.864799193275177

In [88]:
rng.integers(low=0.0, high=10.0, size=None)

np.int64(4)

In [89]:
print(rng.standard_normal())
print(rng.standard_normal(10))

0.7888443445192008
[-1.25666813  0.57585751  1.39897899  1.32229806 -0.29969852  0.90291934
 -1.62158273 -0.15818926  0.44948393 -1.34360107]


In [90]:
rng.binomial(10, 0.5)

3

In [91]:
rng.binomial(10, 0.5, 3)

array([3, 5, 7])

In [92]:
rng.normal(10, 0.5, 3)

array([10.4143166 ,  9.52050584,  9.39530586])

In [93]:
rng.beta(10, 0.5, 3)

array([0.95154327, 0.96875218, 0.99536013])

In [94]:
rng.chisquare(10, 3)

array([ 9.93314308,  9.60000593, 11.33510228])

In [95]:
rng.gamma(10, 3)

34.23236063186882

In [97]:
rng.uniform(0, 10) # low=10, high=3

3.043883872195896