# 6.1 Algebra linear

In [98]:
import numpy as np

As operacoes de algebra linear com a multiplicacao de matrizes,  decomposicao,  determinante,  e outras operacoes matematicas em matrizes quadradas,  sao uma parte importante de muitas biblioptecas de arrays.  A multiplicacao de dois arrays bidimencionais `*` corresponde ao produto de todos os elementos, enquanto as multiplicacoe de matrizes requerem o uso de uma funcao.  logo existe uma funcao `dor` que e tanto um metodo de array quanto uma funcao do namespace `numoy` para a multiplicacao de matiz

In [99]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [100]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [102]:
print(x)

[[1. 2. 3.]
 [4. 5. 6.]]


In [103]:
print(y)

[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


In [106]:
print(x.dot(y))

[[ 28.  64.]
 [ 67. 181.]]


`x.dot(y)` e equivalente ao `np.dot(x,  y)`

In [108]:
print(np.dot(x,  y))

[[ 28.  64.]
 [ 67. 181.]]


Um produto de matrizes entre um array bidimencional e um array undimencional de inverso e detreminante

In [109]:
from numpy.linalg import inv,  qr

In [110]:
rng = np.random.default_rng(12345)

In [111]:
X = rng.standard_normal((5, 5))

In [112]:
mat = X.T @ X

In [114]:
print(mat)

[[ 9.83867527  1.04334204  0.24651754  0.04017965  0.16391486]
 [ 1.04334204  5.11794735 -3.98521413  0.99264687  3.27464142]
 [ 0.24651754 -3.98521413  4.15026075 -2.41299778 -2.74788646]
 [ 0.04017965  0.99264687 -2.41299778  3.97263789 -0.04472489]
 [ 0.16391486  3.27464142 -2.74788646 -0.04472489  6.01956209]]


In [116]:
print(inv(mat))

[[ 0.15548538 -0.36723081 -0.52638547 -0.2300642  -0.04646089]
 [-0.36723081  2.54917814  3.47827334  1.48196722  0.22206454]
 [-0.52638547  3.47827334  5.46389554  2.46214396  0.63467543]
 [-0.2300642   1.48196722  2.46214396  1.38302896  0.33430132]
 [-0.04646089  0.22206454  0.63467543  0.33430132  0.33879566]]


In [117]:
print(mat @ inv(mat))

[[ 1.00000000e+00 -3.92249709e-16  3.65699364e-16  9.40532661e-18
   8.28115661e-18]
 [ 1.38470967e-16  1.00000000e+00 -5.49091918e-16 -1.44925356e-15
  -4.87759366e-16]
 [ 1.32279373e-16  1.98883646e-15  1.00000000e+00  1.88166841e-15
   6.35612717e-17]
 [ 1.07493178e-16 -9.03385668e-16 -1.21906979e-15  1.00000000e+00
  -7.86197612e-17]
 [ 0.00000000e+00  0.00000000e+00  1.77635684e-15  0.00000000e+00
   1.00000000e+00]]


A expressao X.T. dot(X) calcula o produto escalr x com sua transposta X.T

In [ ]:
from numpy.linalg import diag, dot, trace, det, eig, inv, pinv, qr, svd,  solve, lstsq