# 7.2 Simulating Many Random Walks at Once

In [1]:
import numpy as np
import matplotlib.pyplot as plt

We can extend the previous example to simulate many random walks at once. This is a powerful demonstration of NumPy's vectorization capabilities. If you wanted to simulate, say, 5,000 random walks of 1,000 steps, you can generate all of the steps at once.

In [2]:
nwalks = 5000
nsteps = 1000
rng = np.random.default_rng(seed=12345)

## 7.2.1 Generating the Walks

We can generate a 2D array of draws (0 or 1) and then convert them to steps (+1 or -1).

In [3]:
draws = rng.integers(0, 2, size=(nwalks, nsteps)) # 0 or 1
steps = np.where(draws > 0, 1, -1)

Now, we can compute the cumulative sum across the rows to get all 5,000 random walks.

In [4]:
walks = steps.cumsum(axis=1)
print(f"Shape of walks: {walks.shape}")
print(f"A slice of the walks:\n{walks[:5, :10]}")

Shape of walks: (5000, 1000)
A slice of the walks:
[[ 1  0  1  0 -1  0  1  2  3  2]
 [ 1  2  3  4  5  4  5  4  5  6]
 [ 1  0 -1  0  1  0 -1 -2 -3 -4]
 [ 1  2  3  2  1  0 -1 -2 -3 -2]
 [-1  0 -1 -2 -3 -2 -3 -2 -3 -4]]


## 7.2.2 Analyzing the Walks

We can now compute statistics for all 5,000 walks at once.

#### Maximum and Minimum Values
What is the maximum and minimum value obtained across all of the walks?

In [5]:
print(f"Maximum value across all walks: {walks.max()}")
print(f"Minimum value across all walks: {walks.min()}")

Maximum value across all walks: 114
Minimum value across all walks: -120


#### First Passage Time
Let's calculate the first passage time to 30 steps away from the origin. This is more complex as not all walks may reach 30. We can check which walks reached 30 using the `any` method.

In [6]:
hits30 = (np.abs(walks) >= 30).any(axis=1)
print(f"Number of walks that hit 30 or -30: {hits30.sum()}")

Number of walks that hit 30 or -30: 3395


We can then use this boolean array to select the rows of `walks` that actually cross the 30 or –30 level and call `argmax` across axis 1 to get the crossing times.

In [7]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(axis=1)
print(f"Average crossing time for those that hit 30: {crossing_times.mean()}")


Average crossing time for those that hit 30: 500.6182621502209
