# 5.1 Entrada e saida de qarquivos com arrays

In [77]:
import numpy as np

O Numpy pode salvar e carregar dados de e para discos em algumas formas de texto binario. Neste sacao discutirei apenas o formato binario interno do Numpy, ja que a maioria dos usuarios prefere o pandas e outras ferramentas para carregamento e formatos de arquivos para ver mais informacoes

`numpy.save`,  `numpy,load` sao duas principais funcoes de trabalho para salvamento e o carregamento eficiente de dados de arrays em disco. Os arrays sao salvos por padrao em um formato binario bruto descopactado com estacap de arquivo `. npy`

In [78]:
arr = np.arange(10)

In [79]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.save("some_array", arr)

Se o caminho do arquivo nao terminar com `.npy`  a extencao sera acrescida. o array armazena no disco podera entao carregado com o `np.load`

In [89]:
np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Voce pode salvar varios arrays em um arquivo descompactado usando `numpy.savez` e passando os arrays como arsumento nomeados

In [92]:
np.savez("array_archive.npz", a = arr,  b = arr)

In [94]:
arch = np.load('array_archive.npz')

In [96]:
arch["b"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Se os dados apresentados uma voa compactacao pode ser melhor usar `numpy.save_compressed()`

In [97]:
np.savez_compressed("array_archive.npz", a = arr,  b = arr)