# 6.1 Linear Algebra

In [11]:
import numpy as np

Linear algebra, like matrix multiplication, decompositions, determinants, and other square matrix math, is an important part of any array library.

## 6.1.1 Matrix Multiplication

Unlike some other languages, multiplying two 2D arrays with `*` is an element-wise product. Matrix multiplication requires the `dot` function or the `@` operator.

In [12]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(f"x:\n{x}")
print(f"y:\n{y}")

x:
[[1. 2. 3.]
 [4. 5. 6.]]
y:
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


#### `dot` function

In [13]:
print(f"x.dot(y):\n{x.dot(y)}")

x.dot(y):
[[ 28.  64.]
 [ 67. 181.]]


`x.dot(y)` is equivalent to `np.dot(x, y)`.

In [14]:
print(f"np.dot(x, y):\n{np.dot(x, y)}")

np.dot(x, y):
[[ 28.  64.]
 [ 67. 181.]]


#### `@` operator
The `@` operator is another way to do matrix multiplication.

In [15]:
print(f"x @ y:\n{x @ y}")

x @ y:
[[ 28.  64.]
 [ 67. 181.]]


## 6.1.2 `numpy.linalg`

The `numpy.linalg` module has a standard set of matrix decompositions and things like inverse and determinant.

In [16]:
rng = np.random.default_rng(seed=12345)
X = rng.standard_normal((5, 5))
mat = X.T @ X

#### `inv`
Computes the inverse of a square matrix.

In [17]:
print(f"Inverse of mat:\n{np.linalg.inv(mat)}")

Inverse of mat:
[[ 0.15548538 -0.36723081 -0.52638547 -0.2300642  -0.04646089]
 [-0.36723081  2.54917814  3.47827334  1.48196722  0.22206454]
 [-0.52638547  3.47827334  5.46389554  2.46214396  0.63467543]
 [-0.2300642   1.48196722  2.46214396  1.38302896  0.33430132]
 [-0.04646089  0.22206454  0.63467543  0.33430132  0.33879566]]


The product of a matrix and its inverse is the identity matrix.

In [18]:
print(f"mat @ np.linalg.inv(mat):\n{mat @ np.linalg.inv(mat)}")

mat @ np.linalg.inv(mat):
[[ 1.00000000e+00 -3.92249709e-16  3.65699364e-16  9.40532661e-18
   8.28115661e-18]
 [ 1.38470967e-16  1.00000000e+00 -5.49091918e-16 -1.44925356e-15
  -4.87759366e-16]
 [ 1.32279373e-16  1.98883646e-15  1.00000000e+00  1.88166841e-15
   6.35612717e-17]
 [ 1.07493178e-16 -9.03385668e-16 -1.21906979e-15  1.00000000e+00
  -7.86197612e-17]
 [ 0.00000000e+00  0.00000000e+00  1.77635684e-15  0.00000000e+00
   1.00000000e+00]]


#### `qr`
Computes the QR decomposition of a matrix.

In [19]:
q, r = np.linalg.qr(mat)
print(f"q:\n{q}")
print(f"r:\n{r}")

q:
[[-0.99397117  0.06663976  0.03983642  0.05313116 -0.056308  ]
 [-0.10540564 -0.68391044 -0.32234579 -0.58721249  0.26912979]
 [-0.02490491  0.55521203 -0.28617679 -0.13254157  0.76919108]
 [-0.00405923 -0.13611901  0.89236104 -0.14490258  0.40515449]
 [-0.01655981 -0.44837135 -0.12767487  0.78345041  0.41060137]]
r:
[[-9.89835072 -1.53551788  0.12697025 -0.0998577  -0.53915775]
 [ 0.         -7.24670189  6.60676054 -2.53662755 -6.44720911]
 [ 0.          0.         -1.69570009  3.92290656 -1.07111334]
 [ 0.          0.          0.         -0.87162254  3.172517  ]
 [ 0.          0.          0.          0.          1.21194401]]


## 6.1.3 Other Common Functions

#### `diag`
Returns the diagonal elements of a square matrix as a 1D array, or converts a 1D array into a square matrix with the elements on the diagonal.

In [20]:
print(f"Diagonal of mat: {np.diag(mat)}")

Diagonal of mat: [9.83867527 5.11794735 4.15026075 3.97263789 6.01956209]


#### `trace`
Computes the sum of the diagonal elements.

In [21]:
print(f"Trace of mat: {np.trace(mat)}")

Trace of mat: 29.09908335460824


#### `det`
Computes the matrix determinant.

In [22]:
print(f"Determinant of mat: {np.linalg.det(mat)}")

Determinant of mat: 128.48821144048244


#### `eig`
Computes the eigenvalues and eigenvectors of a square matrix.

In [23]:
eigenvalues, eigenvectors = np.linalg.eig(mat)
print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")

Eigenvalues: [12.37440335  9.79692599  0.11120665  1.96405457  4.85249279]
Eigenvectors:
[[-0.22946665 -0.96768886  0.07704665 -0.06395085 -0.02995698]
 [-0.58852279  0.05720493 -0.50807174  0.62605451  0.01695224]
 [ 0.51992082 -0.18491567 -0.77593833 -0.13153123  0.27587639]
 [-0.21711724  0.07860006 -0.35604919 -0.47943335 -0.76815023]
 [-0.53247387  0.14118813 -0.08411664 -0.59733511  0.57676048]]


#### `svd`
Computes the singular value decomposition (SVD).

In [24]:
U, S, VT = np.linalg.svd(mat)
print(f"U:\n{U}")
print(f"S: {S}")
print(f"VT:\n{VT}")


U:
[[-0.22946665  0.96768886  0.02995698  0.06395085 -0.07704665]
 [-0.58852279 -0.05720493 -0.01695224 -0.62605451  0.50807174]
 [ 0.51992082  0.18491567 -0.27587639  0.13153123  0.77593833]
 [-0.21711724 -0.07860006  0.76815023  0.47943335  0.35604919]
 [-0.53247387 -0.14118813 -0.57676048  0.59733511  0.08411664]]
S: [12.37440335  9.79692599  4.85249279  1.96405457  0.11120665]
VT:
[[-0.22946665 -0.58852279  0.51992082 -0.21711724 -0.53247387]
 [ 0.96768886 -0.05720493  0.18491567 -0.07860006 -0.14118813]
 [ 0.02995698 -0.01695224 -0.27587639  0.76815023 -0.57676048]
 [ 0.06395085 -0.62605451  0.13153123  0.47943335  0.59733511]
 [-0.07704665  0.50807174  0.77593833  0.35604919  0.08411664]]
