# 3.1 Funcoes universais: funcoes rapidas de array para todos os elementos

In [98]:
import numpy as np

Uma funcao universal ou `ufunc` e aquelas que executao operacoes em todos os elementos dos dados dos ndarrays. Podemos considera-las como encapsuladores(wrappers) vetorisados rapidos para funcoes simples que recebem uma ou mais valores escalares e produzem um ou mais resultados esclar.

Muitas ufuncs sao transformacoes simmples em todos os elementos como as de `numpy,sqrt` ou `numpy.exp`

In [99]:
arr = np.arange(10)

In [100]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [102]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

Essas funcoes sao chamadas de unfuncs unitarias. Outras como `numpy.add` ou `numpy.maximum`, recebe dois arrays (logo sao funcoes binarias) e retornam um unico array como resultado

In [103]:
rng = np.random.default_rng(seed = 12345)

In [104]:
x = rng.standard_normal(8)

In [105]:
y = rng.standard_normal(8)

In [106]:
x

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331,
       -0.74088465, -1.3677927 ,  0.6488928 ])

In [107]:
y

array([ 0.36105811, -1.95286306,  2.34740965,  0.96849691, -0.75938718,
        0.90219827, -0.46695317, -0.06068952])

In [108]:
np.maximum(x, y)

array([ 0.36105811,  1.26372846,  2.34740965,  0.96849691, -0.07534331,
        0.90219827, -0.46695317,  0.6488928 ])

Nessa exemplo `numpy.maximum` encontrou o valor maximo entre elementos de x e y considerando elemneto a elemento.

Embora nao seja comum, uma ufunc pode retornar multiplos `numpy.modf` e um exemplo: uma versao vetorizada de funcao `math.modf` interna do Python ela retorna as partes fracionaria e inteira de um array de ponto flutuante

In [109]:
arr = rng.standard_normal(7) * 5

In [110]:
arr

array([ 3.94422172, -6.28334067,  2.87928757,  6.99489497,  6.6114903 ,
       -1.49849258,  4.51459671])

In [111]:
remainder, wholw_part = np.modf(arr)

In [112]:
remainder

array([ 0.94422172, -0.28334067,  0.87928757,  0.99489497,  0.6114903 ,
       -0.49849258,  0.51459671])

In [113]:
wholw_part

array([ 3., -6.,  2.,  6.,  6., -1.,  4.])

As ufuncs aveitam um argumneto opcional `out` que as permite atribuir seus resultados a uma array existente em vez de criarem um novo array

In [114]:
out = np.zeros_like(arr)

In [115]:
out

array([0., 0., 0., 0., 0., 0., 0.])

In [116]:
np.add(arr, 1)

array([ 4.94422172, -5.28334067,  3.87928757,  7.99489497,  7.6114903 ,
       -0.49849258,  5.51459671])

In [117]:
np.add(arr, 1, out = out)

array([ 4.94422172, -5.28334067,  3.87928757,  7.99489497,  7.6114903 ,
       -0.49849258,  5.51459671])

In [118]:
out

array([ 4.94422172, -5.28334067,  3.87928757,  7.99489497,  7.6114903 ,
       -0.49849258,  5.51459671])

Novas ufuncs c contunuai sendo adicionados ao numpy por tante consulte a documentacao oficial do numpy caso precise. a seguir mais alguma ufuncs

## unarios

In [119]:
np.abs(arr)

array([3.94422172, 6.28334067, 2.87928757, 6.99489497, 6.6114903 ,
       1.49849258, 4.51459671])

In [120]:
np.fabs(arr)

array([3.94422172, 6.28334067, 2.87928757, 6.99489497, 6.6114903 ,
       1.49849258, 4.51459671])

In [121]:
np.sqrt(arr)

/var/folders/rq/f82lhxqs1p3dtw5q_8fm4hxh0000gn/T/ipykernel_58875/1450069282.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([1.98600648,        nan, 1.69684636, 2.64478638, 2.57128184,
              nan, 2.12475803])

In [122]:
np.exp(arr)

array([5.16361352e+01, 1.86715263e-03, 1.78015863e+01, 1.09104908e+03,
       7.43590369e+02, 2.23466765e-01, 9.13407215e+01])

In [123]:
np.log(arr)

/var/folders/rq/f82lhxqs1p3dtw5q_8fm4hxh0000gn/T/ipykernel_58875/2931416741.py:1: RuntimeWarning: invalid value encountered in log
  np.log(arr)


array([1.37225165,        nan, 1.05754289, 1.94518059, 1.88880909,
              nan, 1.50731586])

In [124]:
np.log10(arr)

/var/folders/rq/f82lhxqs1p3dtw5q_8fm4hxh0000gn/T/ipykernel_58875/2348593099.py:1: RuntimeWarning: invalid value encountered in log10
  np.log10(arr)


array([0.59596132,        nan, 0.45928504, 0.8447812 , 0.82029937,
              nan, 0.65461896])

In [125]:
np.log2(arr)

/var/folders/rq/f82lhxqs1p3dtw5q_8fm4hxh0000gn/T/ipykernel_58875/3610154719.py:1: RuntimeWarning: invalid value encountered in log2
  np.log2(arr)


array([1.97974065,        nan, 1.52571189, 2.8063024 , 2.72497551,
              nan, 2.17459712])

In [127]:
np.log1p(arr)

/var/folders/rq/f82lhxqs1p3dtw5q_8fm4hxh0000gn/T/ipykernel_58875/1276650393.py:1: RuntimeWarning: invalid value encountered in log1p
  np.log1p(arr)


array([1.59821957,        nan, 1.35565152, 2.07880321, 2.02965899,
              nan, 1.70739852])

In [128]:
np.sign(arr)

array([ 1., -1.,  1.,  1.,  1., -1.,  1.])

In [129]:
np.ceil(arr)

array([ 4., -6.,  3.,  7.,  7., -1.,  5.])

In [130]:
np.floor(arr)

array([ 3., -7.,  2.,  6.,  6., -2.,  4.])

In [131]:
np.rint(arr)

array([ 4., -6.,  3.,  7.,  7., -1.,  5.])

In [132]:
np.modf(arr)

(array([ 0.94422172, -0.28334067,  0.87928757,  0.99489497,  0.6114903 ,
        -0.49849258,  0.51459671]),
 array([ 3., -6.,  2.,  6.,  6., -1.,  4.]))

In [133]:
np.isnan(arr)

array([False, False, False, False, False, False, False])

In [134]:
np.isfinite(arr)

array([ True,  True,  True,  True,  True,  True,  True])

In [135]:
np.isinf(arr)

array([False, False, False, False, False, False, False])

In [136]:
np.cos(arr)

array([-0.69481833,  0.99999999, -0.96579482,  0.75724635,  0.94659024,
        0.07224077, -0.19650513])

In [137]:
np.cosh(arr)

array([ 25.82775076, 267.78836117,   8.92888054, 545.52499966,
       371.79585682,   2.34920256,  45.67583478])

In [138]:
np.sin(arr)

array([-7.19185300e-01, -1.55358518e-04,  2.59307475e-01,  6.53129364e-01,
        3.22439019e-01, -9.97387222e-01, -9.80502797e-01])

In [139]:
np.sinh(arr)

array([  25.80838447, -267.78649401,    8.87270577,  545.52408311,
        371.794512  ,   -2.1257358 ,   45.66488676])

In [140]:
np.tan(arr)

array([ 1.03506956e+00, -1.55358520e-04, -2.68491267e-01,  8.62505793e-01,
        3.40632098e-01, -1.38064316e+01,  4.98970587e+00])

In [141]:
np.tanh(arr)

array([ 0.99925018, -0.99999303,  0.99370864,  0.99999832,  0.99999638,
       -0.90487548,  0.99976031])

In [142]:
np.arccos(arr)

/var/folders/rq/f82lhxqs1p3dtw5q_8fm4hxh0000gn/T/ipykernel_58875/1680254270.py:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(arr)


array([nan, nan, nan, nan, nan, nan, nan])

In [143]:
np.arccosh(arr)

/var/folders/rq/f82lhxqs1p3dtw5q_8fm4hxh0000gn/T/ipykernel_58875/3647009934.py:1: RuntimeWarning: invalid value encountered in arccosh
  np.arccosh(arr)


array([2.04892696,        nan, 1.71907095, 2.63317867, 2.57618729,
              nan, 2.18796503])

In [151]:
np.arcsin(arr)

/var/folders/rq/f82lhxqs1p3dtw5q_8fm4hxh0000gn/T/ipykernel_58875/424030015.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(arr)


array([nan, nan, nan, nan, nan, nan, nan])

In [152]:
np.arcsinh(arr)

array([ 2.08109479, -2.53732192,  1.7795665 ,  2.64339854,  2.5876271 ,
       -1.19392676,  2.21250929])

In [153]:
np.arctan(arr)

array([ 1.32249297, -1.41296897,  1.23652161,  1.4287971 ,  1.42068232,
       -0.98232958,  1.35281217])

In [154]:
np.arctanh(arr)

/var/folders/rq/f82lhxqs1p3dtw5q_8fm4hxh0000gn/T/ipykernel_58875/465915096.py:1: RuntimeWarning: invalid value encountered in arctanh
  np.arctanh(arr)


array([nan, nan, nan, nan, nan, nan, nan])

Binarias

In [155]:
np.add(x,y)

array([-1.06276692, -0.6891346 ,  1.47674792,  0.70932367, -0.83473049,
        0.16131362, -1.83474588,  0.58820328])

In [156]:
np.subtract(x,y)

array([-1.78488315,  3.21659152, -3.21807139, -1.22767014,  0.68404387,
       -1.64308293, -0.90083953,  0.70958232])

In [157]:
np.multiply(x,y)

array([-0.51408358, -2.46788863, -2.04379977, -0.25100848,  0.05721474,
       -0.66842485,  0.63869514, -0.03938099])

In [158]:
np.divide(x, y)

array([ -3.94347886,  -0.64711576,  -0.37090319,  -0.26760358,
         0.09921593,  -0.82119937,   2.92918601, -10.69200771])

In [159]:
np.floor_divide(x, y)

array([ -4.,  -1.,  -1.,  -1.,   0.,  -1.,   2., -11.])

In [160]:
np.power(x, y)

/var/folders/rq/f82lhxqs1p3dtw5q_8fm4hxh0000gn/T/ipykernel_58875/1687482090.py:1: RuntimeWarning: invalid value encountered in power
  np.power(x, y)


array([       nan, 0.63311721,        nan,        nan,        nan,
              nan,        nan, 1.02659497])

In [161]:
np.maximum(x, y)

array([ 0.36105811,  1.26372846,  2.34740965,  0.96849691, -0.07534331,
        0.90219827, -0.46695317,  0.6488928 ])

In [162]:
np.fmax(x, y)

array([ 0.36105811,  1.26372846,  2.34740965,  0.96849691, -0.07534331,
        0.90219827, -0.46695317,  0.6488928 ])

In [163]:
np.minimum(x, y)

array([-1.42382504, -1.95286306, -0.87066174, -0.25917323, -0.75938718,
       -0.74088465, -1.3677927 , -0.06068952])

In [164]:
np.fmin(x, y)

array([-1.42382504, -1.95286306, -0.87066174, -0.25917323, -0.75938718,
       -0.74088465, -1.3677927 , -0.06068952])

In [165]:
np.mod(x, y)

array([ 0.02040742, -0.6891346 ,  1.47674792,  0.70932367, -0.07534331,
        0.16131362, -0.43388636, -0.0186919 ])

In [166]:
np.copysign(x, y)

array([ 1.42382504, -1.26372846,  0.87066174,  0.25917323, -0.07534331,
        0.74088465, -1.3677927 , -0.6488928 ])

In [167]:
np.greater(x, y)

array([False,  True, False, False,  True, False, False,  True])

In [168]:
np.greater_equal(x, y)

array([False,  True, False, False,  True, False, False,  True])

In [169]:
np.less(x, y)

array([ True, False,  True,  True, False,  True,  True, False])

In [170]:
np.less_equal(x, y)

array([ True, False,  True,  True, False,  True,  True, False])

In [171]:
np.equal(x, y)

array([False, False, False, False, False, False, False, False])

In [172]:
np.not_equal(x, y)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [173]:
np.logical_and(x, y)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [174]:
np.logical_or(x, y)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [175]:
np.logical_or(x, y)

array([ True,  True,  True,  True,  True,  True,  True,  True])