# 4.6 Unidade e outras logicas de conjuntos

In [46]:
import numpy as np

O Numpy tem algumas operacoes basicas de conjuntos para ndarrays unidimencionais. Uma que e muito usado e `numpy. unique`,  que retorna os valres unicos ordenados de um array:

In [49]:
names = np.array(['Bob',  'Will',  'Joe',  'Bob', 'Will',  'Joe',  'Joe'])

In [50]:
names

array(['Bob', 'Will', 'Joe', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [51]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [52]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [53]:
np.unique(ints)

array([1, 2, 3, 4])

Compare `numpy.unique` com a alternativas em Python puro:


In [54]:
sorted(set(names))

[np.str_('Bob'), np.str_('Joe'), np.str_('Will')]

Em muitos casos a versao do Numpy e mais rapido, e retorma um array Numpy em vez de uma lista Python

Outra funcao ,  `numpy.in1d` verifica se os valores de uma rray sao equivalentes ou de outro array,  retornando um arrau booleano:

In [55]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [59]:
np.isin(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [60]:
np.unique(values)

array([0, 2, 3, 5, 6])

In [61]:
np.intersect1d(values, [2, 3, 6])

array([2, 3, 6])

In [62]:
np.union1d(values, [2, 3, 6])

array([0, 2, 3, 5, 6])

In [63]:
np.isin(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [64]:
np.setdiff1d(values, [2, 3, 6])

array([0, 5])

In [65]:
np.setxor1d(values, [2, 3, 6])

array([0, 5])